# Generated by Django 6.0.4 on 2026-04-25 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('real', 'Real / Authentic'), ('fake', 'Fake / Forged')], max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('total_frames_analyzed', models.IntegerField(default=0)),
                ('fake_frame_count', models.IntegerField(default=0)),
                ('real_frame_count', models.IntegerField(default=0)),
                ('frame_predictions', models.JSONField(default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time_seconds', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('epochs', models.IntegerField(default=50)),
                ('batch_size', models.IntegerField(default=16)),
                ('total_videos', models.IntegerField(default=0)),
                ('total_frames', models.IntegerField(default=0)),
                ('final_accuracy', models.FloatField(blank=True, null=True)),
                ('final_loss', models.FloatField(blank=True, null=True)),
                ('val_accuracy', models.FloatField(blank=True, null=True)),
                ('val_loss', models.FloatField(blank=True, null=True)),
                ('model_path', models.CharField(blank=True, max_length=500)),
                ('training_log', models.JSONField(default=list)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='inputvideos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('label', models.CharField(choices=[('unlabeled', 'Unlabeled'), ('real', 'Real'), ('fake', 'Fake')], default='unlabeled', max_length=20)),
                ('frame_count', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('file_size_mb', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ForgeryRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('original_frame', models.ImageField(upload_to='results/originals/')),
                ('annotated_frame', models.ImageField(upload_to='results/annotated/')),
                ('region_description', models.CharField(default='Suspicious Region', max_length=255)),
                ('confidence', models.FloatField(default=0.0)),
                ('bbox_x', models.IntegerField(default=0)),
                ('bbox_y', models.IntegerField(default=0)),
                ('bbox_width', models.IntegerField(default=0)),
                ('bbox_height', models.IntegerField(default=0)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='detector.analysisresult')),
            ],
            options={
                'ordering': ['frame_number'],
            },
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='detector.video'),
        ),
    ]
